name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: twoeqaul0/auto-assign-bot@v1.2.1
        with:
          configuration-path: '.github/auto-assign.yml'
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            assignees: mkpro118
            numOfAssignee: 1
