name: Auto Assign PRs
on:
  pull_request:
    types: [opened]
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: twoequal0/auto-assign-bot@v1.3.0
        with:
          configuration-path: '.github/auto-assign-pr.yml'
