name: Add New User Story

on:
  issues:
    types: [opened]

permissions: write-all

env:
  MK_USERNAME: ${{ secrets.MK_USERNAME }}
  MK_EMAIL: ${{ secrets.MK_EMAIL }}
  PYTHONPATH: ${{ github.workspace }}/.github/scripts/

jobs:
  add-user-story:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'user-story')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Use token to allow force push
          token: ${{ secrets.MK_TOKEN }}
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Add User Story to Document
        if: ${{ github.event_name == 'issues' }}
        run: |
          python .github/scripts/user_story.py create -c "${{ github.event.issue.body }}" \
            -n ${{ github.event.issue.number }} --url ${{ github.event.issue.html_url }} \

